project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550 - Final Project"
  site-url: "https://musa-550-fall-2023.github.io/final_project_EP" 
  repo-url: https://github.com/MUSA-550-Fall-2023/quarto-website-template 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Emmy Park"

  sidebar:
    logo: "images/cat.jpeg"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/emmyhp
        text: "EP GitHub"
      - icon: linkedin
        href: www.linkedin.com/in/emmy-park-5260b0183
        text: "EP LinkedIn"         

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - section: analysis/index.qmd
        contents:
          - FinalProject/Step1.ipynb
          - FinalProject/Step2.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




