---
title: "MUSA 550 - Final Project"
subtitle: "Emmy Park"
---

## Predicting Philadelphia's 2024 Street Paving Plan

### Introduction

Each year, the Philadelphia Streets Department releases their annual Street Paving Program and List, detailing the paving process and lists streets that the department will pave that year.

When I interned for the Street Department, my coworkers joked that the way the list was decided was one person randomly choosing whichever streets they thought needed it. I wanted to see whether or not that was actually the truth and if I can use existing data about to test it.

### Data Sources

I chose to use data about the street's physical and safety conditions to create the model. These data features include:

**1.** **311 Calls about Potholes ([2022](https://opendataphilly.org/datasets/311-service-and-information-requests/)) ([2023](https://iframe.publicstuff.com/#?client_id=242))**

More calls about potholes likely means that the street needs to be repaved more than others. However, it should be noted that 311 calls are a biased data source. 311 callers tend to be [whiter and richer](https://hunterurbanreview.commons.gc.cuny.edu/the-value-of-311-data/).
        
**2.** [**Whether Street is a Non-Thru Street for Trucks**](https://opendataphilly.org/datasets/non-thru-streets-for-trucks/)

Without information on traffic levels for each street, we can use whether the street is open to trucks as a substitute.

**3.** [**Street Classification**](https://opendataphilly.org/datasets/complete-streets/)

Without information on traffic levels for each street, we can use street capacity as a substitute.

**4.** [**Number of Fatal Crashes**](https://opendataphilly.org/datasets/fatal-crashes/) 

OTIS often aligns their restriping/safety plans with streets that are about to be repaved. A higher share of crashes would indicate a bigger need for safety interventions.

**5.** [**Level of Bike Stress**](https://www.dvrpc.org/webmaps/bike-lts/analysis/) 

The LTS classification scheme is DVRPC's estimation of comfort of bicyclists in traffic depending on number of lanes, effective vehicle speed, and presence/type of bicycle facility. Much like the crashes, a higher stress level should indicate a bigger need for bike safety interventions.

**6.** **Whether Street Was Repaved in Previous Year ([2022](https://www.phila.gov/media/20220323163849/streetpaving2022booklet.pdf))([2023](https://www.phila.gov/media/20230426182237/streetpaving2023-guide.pdf))**

A street that was repaved in the previous year would likely not need to be repaved in this round of repaving. 

